=== Krkan/TNM065-labs/project/users.dtd
<!ELEMENT ad_service (users?,ads?)>

<!ELEMENT users (user+)>
<!ELEMENT user (user_name,name, last_name, date_of_reg, email)>
<!ELEMENT ads (ad+)>
<!ELEMENT ad (user_name, post_id, description, pic, date_added, item_location, title, price)>


<!ELEMENT user_name (#PCDATA)>
<!ATTLIST user_name is_admin (yes | no) #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT date_of_reg (#PCDATA)>
<!ELEMENT email (#PCDATA)>


<!ELEMENT post_id (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT pic (#PCDATA)>
<!ELEMENT date_added (#PCDATA)>
<!ATTLIST ad category (Computer | Car | Furniture | Clothing | Books | Other) #REQUIRED>
<!ELEMENT item_location (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== Krkan/TNM065-labs/project/temp/users.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ad_service SYSTEM "http://84.216.133.49/TNM065/project-dtd/users.dtd">

<ad_service>

<users>
<user>
<user_name is_admin="no">kek</user_name>
<name>fake</name>
<last_name>lname</last_name>
<date_of_reg>some date</date_of_reg>
<email>sss@hotmail.com</email>
</user>

</users>


<ads>
<ad category="Car">
<user_name>name</user_name>
<post_id>24234</post_id>
<description>des</description>
<image>derp.jpg</image>
<date_added>some date</date_added>
<item_location>loc</item_location>
<title>derp</title>
</ad>
</ads>

</ad_service>
